services:
  - type: web
    name: chackshop
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: LINE_NOTIFY_TOKEN
        sync: false
      - key: LINE_PAY_CHANNEL_ID
        sync: false
      - key: LINE_PAY_CHANNEL_SECRET
        sync: false
